### ISSUE TITLE
Should spawning new infantry allow you to capture

### ISSUE THREAD

**Issue by acunniffe** [acunniffe/ghq#109]
Played a game with opponent on my back rank 

Can I spawn one infantry on each side and capture?

**Comment by APTy** [comment]
My opinion: no, with some subtlety

For example, let's say red has an armored infantry on blue's back rank (`f8`):

<img width="628" alt="Screenshot 2024-11-16 at 8 01 04 PM" src="https://github.com/user-attachments/assets/e0eeb03e-9040-4fe8-9c49-5fab4a01de61">

## Adding two infantry from reserve: no capture

Now let's say I add two pieces from my reserve on either side (`g8` and `e8`):

<img width="638" alt="Screenshot 2024-11-16 at 8 01 10 PM" src="https://github.com/user-attachments/assets/1037b045-aa76-4fe8-82cf-731d3dcf3e1e">

The rules state that "The same piece may not be used in more than one Action, but the same action can be taken
multiple times with different pieces."

In this case, after reinforcing on `g8` and `e8`, those pieces have already been action'ed on, so they can't then make a "move" or even some kind of "auto capture" (which would only happen at the start of your turn).

## Adding one infantry from reserve, then moving an existing piece: yes capture

Instead if we already had an infantry on `e7`, we could add a single infantry on `g8`, and then move to `f7` to capture:

<img width="630" alt="Screenshot 2024-11-16 at 8 01 58 PM" src="https://github.com/user-attachments/assets/be7151bf-be7c-4dda-bd99-db6d0b3c2e77">

This feels legal because engagement is always automatic and implicit after any infantry move, so it feels natural that the infantry on `g8` and `f8` would become immediately engaged, leaving blue with the ability to move to `f7` for the 2on1.

**Comment by boxed** [comment]
My opinion would be that it should capture, with the justification that a reinforce is a move onto the given square, just from outside the board.

I also like that this makes it more dangerous to paratroop very deep into enemy territory, which intuitively seems logical to me.

**Comment by acunniffe** [comment]
Great points. My take: they capture. 

Allowing it definitely adds some interesting dynamics to the endgame. You could imagine reinforcing being a powerful defensive tool if the opponent is cornering you. 

Knowing that's coming changed how you attack, just like knowing your opponent has a ready airborne unit does. 

In the official rules this is never mentioned, but the guiding principle of "one capture per move" is everywhere.

**Comment by APTy** [comment]
These are good points. Here's some excerpts from the rules and then my new thoughts at the bottom:

> ## Taking a Turn
> The blue player takes the first turn. On your turn you perform two steps:
> • Captures: If the other player moved pieces where they could be captured, or left them where
> they were being attacked, remove them now (see Capturing on pg 4).
> • Take three Actions: Captures may also occur during these Actions.
> 
> There are three possible actions:
> A. Move a piece on the board
> B. Place a piece from your Reserve onto any empty square on their back row
> C. Rotate an artillery to face a new direction
> 
> IMPORTANT: The same piece may not be used in more than one Action, but the same action can be taken
> multiple times with different pieces. Example: For your first action you place a Regular infantry from your
> Reserve into the back row. That same infantry can not be moved during the second or third action. You can,
> however, place another piece from your Reserve into play with your second and even third actions.

> ## Infantry Capturing Infantry
> If there is just one friendly and enemy infantry adjacent to each other, they
> are engaged and do not capture each other. It is considered a standoff. The
> players may rotate the infantry to face each other to make it simpler to track
> which pieces are engaged.
> 
> If a second infantry is moved adjacent to an enemy that is already in a
> standoff, the enemy will be captured. HOWEVER, if the moving piece is
> adjacent to more than one enemy piece, at least one of which is not engaged,
> the moving piece must engage that enemy and cannot capture (See
> example on pg 6).
> 
> An infantry can only capture one piece when it moves. If it moves into
> a position where it can capture more than one piece, the moving
> player chooses which piece to capture.

## Discussion

First, let's not be too much of rules fundamentalists, instead we should try to implement what feels fun, fair, and in the spirit of the game. With that in mind:

A critical part from the first section is **Captures may also occur during these Actions.** which seems to imply that yes, you should be able to capture after of the 3 actions (subject to engagement rules).

A critical piece of the second section is **If a second infantry is moved adjacent to an enemy that is already in a
> standoff, the enemy will be captured.** and  **An infantry can only capture one piece when it moves.** These could imply that you need to _move_ the infantry, not simply place it from your reserve.

Still, I think I agree with you both, that this feels like a good defensive capability to have, and ensures some balance of somehow being overrun even when you still have troops in your reserve.

Let's do it!

(and if it feels unfair later or feels like it promotes turtling too much, we can adjust)
