### ISSUE TITLE
If a player times out they won't lose unless they make their final turn/move

### ISSUE THREAD

**Issue by acunniffe** [acunniffe/ghq#159]
Not the worst bug at this stage, but does let someone bail and save elo

**Comment by APTy** [comment]
Yeah we should try for an experience like chess.com where if the opponent is offline for more than 30 seconds then they automatically lose the game. Some of these things are tricky because they're not strictly "game rules" but exist outside of the game, but I think we can get something close

**Comment by APTy** [comment]
There's some interesting convo in https://github.com/boardgameio/boardgame.io/issues/92 about using a `setTimeout` at the start of the turn to trigger an "end turn" at some future point, but that seems to break if the server gets restarted.

Also saw that we should likely be using some kind of [clock.now()](https://github.com/turnbasedgames/urturn/pull/193) instead of `Date.now()` as it is server-client synced
